// <auto-generated />
using System;
using KeciApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeciApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125165513_UserIsActiveMigration")]
    partial class UserIsActiveMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeciApp.API.Models.Affirmations", b =>
                {
                    b.Property<int>("AffirmationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AffirmationId"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("AffirmationId");

                    b.ToTable("Affirmations", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Answers", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Aphorisms", b =>
                {
                    b.Property<int>("AphorismId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AphorismId"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("AphorismId");

                    b.ToTable("Aphorisms", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.ApiLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("KeciApp.API.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PdfLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.DailyContent", b =>
                {
                    b.Property<int>("DailyContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyContentId"));

                    b.Property<int>("AffirmationId")
                        .HasColumnType("integer");

                    b.Property<int>("AporismId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOrder")
                        .HasColumnType("integer");

                    b.HasKey("DailyContentId");

                    b.HasIndex("AffirmationId");

                    b.HasIndex("AporismId");

                    b.ToTable("DailyContent", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Favorites", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteId"));

                    b.Property<int?>("AffirmationId")
                        .HasColumnType("integer");

                    b.Property<int?>("AphorismId")
                        .HasColumnType("integer");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<int>("FavoriteType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FavoriteId");

                    b.HasIndex("AffirmationId");

                    b.HasIndex("AphorismId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovieId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("MovieId");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Music", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MusicId"));

                    b.Property<string>("MusicDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusicTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusicURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("MusicId");

                    b.ToTable("Musics", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Notes", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoteId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NoteId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.PodcastEpisodes", b =>
                {
                    b.Property<int>("EpisodesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EpisodesId"));

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isVideo")
                        .HasColumnType("boolean");

                    b.HasKey("EpisodesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("PodcastEpisodes", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.PodcastSeries", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeriesId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isVideo")
                        .HasColumnType("boolean");

                    b.HasKey("SeriesId");

                    b.ToTable("PodcastSeries", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Questions", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("isAnswered")
                        .HasColumnType("boolean");

                    b.HasKey("QuestionId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyContentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("KeciTimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubscriptionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("WeeklyContentId")
                        .HasColumnType("integer");

                    b.Property<bool>("dailyOrWeekly")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.HasIndex("DailyContentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WeeklyContentId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.UserProgress", b =>
                {
                    b.Property<int>("UserProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserProgressId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyContentId")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekId")
                        .HasColumnType("integer");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("UserProgressId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DailyContentId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("WeekId");

                    b.HasIndex("UserId", "ArticleId")
                        .IsUnique()
                        .HasFilter("\"ArticleId\" IS NOT NULL");

                    b.HasIndex("UserId", "DailyContentId")
                        .IsUnique()
                        .HasFilter("\"DailyContentId\" IS NOT NULL");

                    b.HasIndex("UserId", "EpisodeId")
                        .IsUnique()
                        .HasFilter("\"EpisodeId\" IS NOT NULL");

                    b.HasIndex("UserId", "WeekId")
                        .IsUnique()
                        .HasFilter("\"WeekId\" IS NOT NULL");

                    b.ToTable("UserProgress", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.UserSeriesAccess", b =>
                {
                    b.Property<int>("UserSeriesAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserSeriesAccessId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentAccessibleSequence")
                        .HasColumnType("integer");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserSeriesAccessId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("UserId", "SeriesId", "ArticleId")
                        .IsUnique();

                    b.ToTable("UserSeriesAccesses", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.WeeklyContent", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeekId"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("MusicId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekOrder")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("WeekId");

                    b.HasIndex("MovieId");

                    b.HasIndex("MusicId");

                    b.HasIndex("TaskId");

                    b.HasIndex("WeeklyQuestionId");

                    b.ToTable("WeeklyContents", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.WeeklyQuestion", b =>
                {
                    b.Property<int>("WeeklyQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeeklyQuestionId"));

                    b.Property<string>("WeeklyQuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("WeeklyQuestionId");

                    b.ToTable("WeeklyQuestions", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.WeeklyQuestionAnswer", b =>
                {
                    b.Property<int>("WeeklyQuestionAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeeklyQuestionAnswerId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WeeklyQuestionAnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeeklyQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("WeeklyQuestionAnswerId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeeklyQuestionId");

                    b.ToTable("WeeklyQuestionAnswers");
                });

            modelBuilder.Entity("KeciApp.API.Models.WeeklyTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("KeciApp.API.Models.Answers", b =>
                {
                    b.HasOne("KeciApp.API.Models.Questions", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeciApp.API.Models.DailyContent", b =>
                {
                    b.HasOne("KeciApp.API.Models.Affirmations", "Affirmations")
                        .WithMany()
                        .HasForeignKey("AffirmationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.Aphorisms", "Aphorisms")
                        .WithMany()
                        .HasForeignKey("AporismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affirmations");

                    b.Navigation("Aphorisms");
                });

            modelBuilder.Entity("KeciApp.API.Models.Favorites", b =>
                {
                    b.HasOne("KeciApp.API.Models.Affirmations", "Affirmations")
                        .WithMany()
                        .HasForeignKey("AffirmationId");

                    b.HasOne("KeciApp.API.Models.Aphorisms", "Aphorisms")
                        .WithMany()
                        .HasForeignKey("AphorismId");

                    b.HasOne("KeciApp.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("KeciApp.API.Models.PodcastEpisodes", "PodcastEpisode")
                        .WithMany("Favorites")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affirmations");

                    b.Navigation("Aphorisms");

                    b.Navigation("Article");

                    b.Navigation("PodcastEpisode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeciApp.API.Models.Notes", b =>
                {
                    b.HasOne("KeciApp.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("KeciApp.API.Models.PodcastEpisodes", "PodcastEpisode")
                        .WithMany("Notes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("PodcastEpisode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeciApp.API.Models.PodcastEpisodes", b =>
                {
                    b.HasOne("KeciApp.API.Models.PodcastSeries", "PodcastSeries")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodcastSeries");
                });

            modelBuilder.Entity("KeciApp.API.Models.Questions", b =>
                {
                    b.HasOne("KeciApp.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("KeciApp.API.Models.PodcastEpisodes", "Episodes")
                        .WithMany("Questions")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Episodes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeciApp.API.Models.RefreshToken", b =>
                {
                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeciApp.API.Models.User", b =>
                {
                    b.HasOne("KeciApp.API.Models.DailyContent", "DailyContent")
                        .WithMany()
                        .HasForeignKey("DailyContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeciApp.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.WeeklyContent", "WeeklyContent")
                        .WithMany()
                        .HasForeignKey("WeeklyContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyContent");

                    b.Navigation("Role");

                    b.Navigation("WeeklyContent");
                });

            modelBuilder.Entity("KeciApp.API.Models.UserProgress", b =>
                {
                    b.HasOne("KeciApp.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("KeciApp.API.Models.DailyContent", "DailyContent")
                        .WithMany()
                        .HasForeignKey("DailyContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeciApp.API.Models.PodcastEpisodes", "PodcastEpisodes")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.WeeklyContent", "WeeklyContent")
                        .WithMany()
                        .HasForeignKey("WeekId");

                    b.Navigation("Article");

                    b.Navigation("DailyContent");

                    b.Navigation("PodcastEpisodes");

                    b.Navigation("User");

                    b.Navigation("WeeklyContent");
                });

            modelBuilder.Entity("KeciApp.API.Models.UserSeriesAccess", b =>
                {
                    b.HasOne("KeciApp.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("KeciApp.API.Models.PodcastSeries", "PodcastSeries")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany("UserSeriesAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("PodcastSeries");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeciApp.API.Models.WeeklyContent", b =>
                {
                    b.HasOne("KeciApp.API.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.Music", "Music")
                        .WithMany()
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.WeeklyTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.WeeklyQuestion", "WeeklyQuestion")
                        .WithMany()
                        .HasForeignKey("WeeklyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Music");

                    b.Navigation("Task");

                    b.Navigation("WeeklyQuestion");
                });

            modelBuilder.Entity("KeciApp.API.Models.WeeklyQuestionAnswer", b =>
                {
                    b.HasOne("KeciApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeciApp.API.Models.WeeklyQuestion", "WeeklyQuestion")
                        .WithMany()
                        .HasForeignKey("WeeklyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WeeklyQuestion");
                });

            modelBuilder.Entity("KeciApp.API.Models.PodcastEpisodes", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Notes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KeciApp.API.Models.PodcastSeries", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("KeciApp.API.Models.Questions", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("KeciApp.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KeciApp.API.Models.User", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Favorites");

                    b.Navigation("Notes");

                    b.Navigation("Questions");

                    b.Navigation("UserSeriesAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
